-- Core schema for lyricsync web app.
--
-- This file is the source of truth for the database structure. It mirrors the
-- migration applied to the live Supabase project (initial_schema, 2026-05-24)
-- and can be re-applied verbatim to a fresh project to recreate the schema.
--
-- All four tables enable Row Level Security. Policies scope every row to the
-- authenticated user's email via the JWT, so the anon/browser session can
-- only read/write rows owned by the logged-in user. Server-side code that
-- uses the service-role key bypasses RLS by design.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Tables
-- ---------------------------------------------------------------------------

-- Project: a collection of source clips, transcripts, and (Phase 2) stories.
--
-- status values:
--   'uploading'    — at least one clip is still uploading to R2
--   'transcribing' — all clips uploaded; per-clip Whisper jobs running
--   'transcribed'  — alignment/merge done; transcript is readable
--   'rendering'    — a cut is being rendered
--   'done'         — a cut has finished rendering
--   'error'        — terminal failure; see app logs
create table projects (
  id         uuid primary key default gen_random_uuid(),
  owner      text not null,
  name       text not null,
  status     text not null default 'uploading',
  created_at timestamptz not null default now()
);

-- Clip: a single source video uploaded by the user.
--
-- status values:
--   'uploading'           — presigned PUT in flight or not yet started
--   'uploading_complete'  — client confirmed PUT succeeded; awaiting transcribe kickoff
--   'transcribing'        — Whisper job running
--   'aligned'             — transcript merged into the project timeline
--   'error'               — terminal failure for this clip
create table clips (
  id                uuid primary key default gen_random_uuid(),
  project_id        uuid not null references projects(id) on delete cascade,
  r2_key            text,
  filename          text,
  duration_secs     double precision,
  global_start      double precision,
  transcript_r2_key text,
  status            text not null default 'uploading'
);

-- Story: a chosen cut (set of time ranges) that gets rendered into a video.
-- Phase 1 stories are created manually via the range picker; Phase 2 will
-- have them generated by an LLM, which is why 'generating' is the default
-- (forward-compatibility — Phase 1 callers should write 'rendering' on insert).
--
-- status values:
--   'generating'   — (Phase 2) LLM is producing the story
--   'rendering'    — render job running
--   'done'         — output MP4 is in R2 (render_r2_key set)
--   'error'        — terminal failure
create table stories (
  id            uuid primary key default gen_random_uuid(),
  project_id    uuid not null references projects(id) on delete cascade,
  title         text,
  description   text,
  ranges_json   jsonb,
  render_r2_key text,
  status        text not null default 'generating',
  created_at    timestamptz not null default now()
);

-- Feedback: free-text notes attached to a story, used as additional context
-- when re-generating a story in Phase 2. Not consumed in Phase 1.
create table feedback (
  id         uuid primary key default gen_random_uuid(),
  story_id   uuid not null references stories(id) on delete cascade,
  text       text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

create index clips_project_id_idx    on clips(project_id);
create index stories_project_id_idx  on stories(project_id);
create index feedback_story_id_idx   on feedback(story_id);
create index projects_owner_idx      on projects(owner);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table projects enable row level security;
alter table clips    enable row level security;
alter table stories  enable row level security;
alter table feedback enable row level security;

create policy projects_owner_all on projects
  for all to authenticated
  using (owner = (auth.jwt() ->> 'email'))
  with check (owner = (auth.jwt() ->> 'email'));

create policy clips_owner_all on clips
  for all to authenticated
  using (exists (select 1 from projects p where p.id = clips.project_id and p.owner = (auth.jwt() ->> 'email')))
  with check (exists (select 1 from projects p where p.id = clips.project_id and p.owner = (auth.jwt() ->> 'email')));

create policy stories_owner_all on stories
  for all to authenticated
  using (exists (select 1 from projects p where p.id = stories.project_id and p.owner = (auth.jwt() ->> 'email')))
  with check (exists (select 1 from projects p where p.id = stories.project_id and p.owner = (auth.jwt() ->> 'email')));

create policy feedback_owner_all on feedback
  for all to authenticated
  using (exists (select 1 from stories s join projects p on p.id = s.project_id where s.id = feedback.story_id and p.owner = (auth.jwt() ->> 'email')))
  with check (exists (select 1 from stories s join projects p on p.id = s.project_id where s.id = feedback.story_id and p.owner = (auth.jwt() ->> 'email')));
